In [63]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

In [64]:
data = pd.read_csv("data/Purchased_Dataset.csv", delimiter=",")
data.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [30]:
data = data.drop(columns=['User ID'])
data.head(2)

Gender  Age  EstimatedSalary  Purchased
0   Male   19            19000          0
1   Male   35            20000          0

In [31]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [32]:
X

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [33]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [34]:
gender = pd.get_dummies(X['Gender'],drop_first=True)
X = pd.concat([X, gender], axis=1)
X = X.drop(columns=['Gender'])
X.head(2)

Age  EstimatedSalary  Male
0   19            19000  True
1   35            20000  True

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(x_train)
scaled_data

array([[-1.06675246, -0.38634438, -1.        ],
       [ 0.79753468, -1.22993871,  1.        ],
       [ 0.11069205,  1.853544  , -1.        ],
       [ 0.60129393, -0.90995465, -1.        ],
       [ 1.87685881, -1.28811763, -1.        ],
       [-0.57615058,  1.44629156,  1.        ],
       [ 0.3069328 , -0.53179168,  1.        ],
       [ 0.99377543,  0.10817643,  1.        ],
       [-1.16487283,  0.45724994,  1.        ],
       [-1.55735433,  0.31180264,  1.        ],
       [ 1.0918958 ,  0.45724994,  1.        ],
       [-0.18366908, -0.47361276, -1.        ],
       [ 0.20881242, -0.32816546,  1.        ],
       [ 0.3069328 ,  0.28271318, -1.        ],
       [-1.16487283, -1.57901222,  1.        ],
       [ 0.11069205,  0.25362372, -1.        ],
       [ 2.07309956,  1.73718616,  1.        ],
       [ 0.40505317, -0.18271817,  1.        ],
       [ 1.4843773 ,  2.11534913, -1.        ],
       [-0.37990983,  1.21357589,  1.        ],
       [ 1.87685881,  1.50447048, -1.   

In [45]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=4)
model = KNN.fit(x_train, y_train)

In [46]:
scaled_pred_data = scaler.transform(x_test)
pred_results = model.predict(scaled_pred_data)

/Users/joeljoseph26/Documents/Education/Machine_and_Deep_Learning/ML-DL-projects/Classification-Projects/Classification-Projects/env/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [47]:
pred_results

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
print(confusion_matrix(y_test, pred_results))
print(accuracy_score(y_test, pred_results))
print(precision_score(y_test, pred_results))
print(recall_score(y_test, pred_results))

[[52  0]
 [28  0]]
0.65
0.0
0.0


/Users/joeljoseph26/Documents/Education/Machine_and_Deep_Learning/ML-DL-projects/Classification-Projects/Classification-Projects/env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# With Cross Validation: (Cross Val Score)

In [62]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=5)
model_performance = cross_val_score(KNN, x_train, y_train, cv=10, n_jobs=-1, scoring='precision')
model_performance


array([0.875     , 0.61538462, 0.875     , 1.        , 0.8       ,
       0.75      , 0.75      , 0.66666667, 0.7       , 0.8       ])

In [58]:
model_average = model_performance.mean()
model_average

0.809375

In [59]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=5)
model_neighbour_5 = KNN.fit(x_train, y_train)
y_pred = model_neighbour_5.predict(x_test)

In [60]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

[[46  6]
 [ 8 20]]
0.825
0.7692307692307693
0.7142857142857143
