In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import keras
import tensorflow as tf
%matplotlib inline


In [13]:
data = pd.read_csv("data/BankCustomers.csv", delimiter=",")
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [14]:
data = data.drop(columns=['RowNumber','CustomerId','Surname'], axis=1)
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [23]:
data.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [15]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [16]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [18]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [19]:
X = pd.get_dummies(X, columns=['Geography'], drop_first=True)
X = pd.get_dummies(X, columns=['Gender'], drop_first=True)

In [20]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0                  1        101348.88              False            False   
1                  1        112542.58              False             True   
2                  0        113931.57              False            False   
3                  0         93826.63              False            False   
4                  1         79084.10              False             True   
...              ...              ...                ...              ...   
9995               0         96270.64              False            False   
9996               1        101699.77              False            False   
9997               1         42085.58              False            False   
9998               0         92888.52               True            False   
9999               0         38190.78              False            False   

      Gender_Male  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
9995         True  
9996         True  
9997        False  
9998         True  
9999        False  

[10000 rows x 11 columns]

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled_data = scaler.fit_transform(x_train)

In [28]:
x_train_scaled_data

array([[-8.52244794e-01,  1.89512668e-01, -1.04052486e+00, ...,
        -5.81969145e-01,  1.74778116e+00,  9.12327143e-01],
       [-2.87475013e+00,  2.84518393e-01,  6.89646172e-01, ...,
        -5.81969145e-01, -5.72154011e-01,  9.12327143e-01],
       [ 1.00515806e+00,  1.42458708e+00, -6.94490651e-01, ...,
         1.71830416e+00, -5.72154011e-01,  9.12327143e-01],
       ...,
       [-1.36819003e+00, -4.98780052e-04, -3.48456445e-01, ...,
        -5.81969145e-01,  1.74778116e+00,  9.12327143e-01],
       [-9.14158223e-01, -6.65538850e-01, -1.73259327e+00, ...,
        -5.81969145e-01, -5.72154011e-01, -1.09609805e+00],
       [ 1.42823316e+00, -1.23557319e+00, -2.42223944e-03, ...,
        -5.81969145e-01, -5.72154011e-01,  9.12327143e-01]])

In [29]:
x_train_scaled_data.shape

(8000, 11)

In [33]:
x_test.shape

(2000, 11)

In [34]:
y_train.shape

(8000,)

In [35]:
y_test.shape

(2000,)

In [37]:
from keras.models import  Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

ANN = Sequential()
ANN.add(Dense(activation= 'relu',kernel_initializer='uniform', units=6, input_dim=11))
ANN.add(Dense(activation= 'relu',kernel_initializer='uniform', units=6))
ANN.add(Dense(activation= 'sigmoid',kernel_initializer='uniform', units=1))

ANN.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [43]:
ANN.fit(x_train_scaled_data,y_train, batch_size=32, epochs=10)

Epoch 1/10
  1/250 [..............................] - ETA: 2s - loss: 0.3545 - accuracy: 0.8125

250/250 [==============================] - 2s 9ms/step - loss: 0.4122 - accuracy: 0.8330
Epoch 2/10
250/250 [==============================] - 1s 6ms/step - loss: 0.4116 - accuracy: 0.8322
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.4115 - accuracy: 0.8324
Epoch 4/10
250/250 [==============================] - 1s 4ms/step - loss: 0.4107 - accuracy: 0.8324
Epoch 5/10
250/250 [==============================] - 2s 7ms/step - loss: 0.4105 - accuracy: 0.8317
Epoch 6/10
250/250 [==============================] - 2s 7ms/step - loss: 0.4104 - accuracy: 0.8326
Epoch 7/10
250/250 [==============================] - 3s 10ms/step - loss: 0.4096 - accuracy: 0.8336
Epoch 8/10
250/250 [==============================] - 2s 10ms/step - loss: 0.4092 - accuracy: 0.8331
Epoch 9/10
250/250 [==============================] - 4s 16ms/step - loss: 0.4091 - accuracy: 0.8335
Epoch 10/10
250/250 [==============================] - 2s 10ms/step - loss: 0.4088 - accuracy: 0.8329


In [44]:
x_test_scaled_data = scaler.transform(x_test)
y_pred = ANN.predict(x_test_scaled_data)

63/63 [==============================] - 1s 9ms/step


In [46]:
y_pred


array([[0.04252332],
       [0.0462498 ],
       [0.16231246],
       ...,
       [0.05726985],
       [0.24064824],
       [0.02910184]], dtype=float32)

In [47]:
y_pred = (y_pred > 0.5)

In [48]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


0.8475
0.7547169811320755
0.31088082901554404
0.44036697247706424
[[1575   39]
 [ 266  120]]
