In [1]:
import numpy as np
import matplotlib.pyplot as plt
import  pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv("data/Advertising_data.csv", delimiter=",")
data

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [3]:
data = data.drop(columns=['User ID'], axis=1)
data.head(5)

Gender   Age  EstimatedSalary  Purchased
0    Male  19.0          19000.0          0
1    Male  35.0          20000.0          0
2  Female  26.0          43000.0          0
3  Female  27.0          57000.0          0
4    Male  19.0          76000.0          0

In [4]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [5]:
X

Gender   Age  EstimatedSalary
0      Male  19.0          19000.0
1      Male  35.0          20000.0
2    Female  26.0          43000.0
3    Female  27.0          57000.0
4      Male  19.0          76000.0
..      ...   ...              ...
395  Female  46.0          41000.0
396    Male  51.0          23000.0
397  Female  50.0          20000.0
398    Male  36.0          33000.0
399  Female  49.0          36000.0

[400 rows x 3 columns]

In [6]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [7]:
X = pd.get_dummies(X, columns=['Gender'], drop_first=True)
X

Age  EstimatedSalary  Gender_Male
0    19.0          19000.0         True
1    35.0          20000.0         True
2    26.0          43000.0        False
3    27.0          57000.0        False
4    19.0          76000.0         True
..    ...              ...          ...
395  46.0          41000.0        False
396  51.0          23000.0         True
397  50.0          20000.0        False
398  36.0          33000.0         True
399  49.0          36000.0        False

[400 rows x 3 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled_data = scaler.fit_transform(x_train)
x_scaled_data

array([[-0.84252154,  0.1301563 ,  1.02166316],
       [ 0.04175763,  0.2777019 , -0.97879618],
       [ 0.72953032, -1.31579061,  1.02166316],
       [ 1.61380949,  1.10395728, -0.97879618],
       [ 0.82778356, -1.40431797,  1.02166316],
       [-1.43204099, -1.25677236, -0.97879618],
       [-0.05649561,  0.1301563 ,  1.02166316],
       [ 0.43477059, -0.16493491,  1.02166316],
       [-0.2530021 ,  0.01211982, -0.97879618],
       [ 1.31904976,  2.22530386, -0.97879618],
       [ 0.14001087,  0.74984783,  1.02166316],
       [-1.33378775,  0.54328399, -0.97879618],
       [ 2.00682245,  0.72033871, -0.97879618],
       [-1.23553451, -1.43382709,  1.02166316],
       [ 0.33651735, -0.34198963,  1.02166316],
       [-0.94077478,  0.54328399,  1.02166316],
       [ 0.43477059,  0.2777019 , -0.97879618],
       [ 0.43477059,  1.10395728, -0.97879618],
       [ 0.82778356,  0.74984783, -0.97879618],
       [ 0.9260368 ,  1.25150288, -0.97879618],
       [-0.44950858, -1.25677236, -0.978

In [10]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
model = classifier.fit(x_scaled_data, y_train)

In [11]:
x_test_scaled_data = scaler.transform(x_test)

In [12]:
y_pred = model.predict(x_test_scaled_data)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [13]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(precision_score(y_pred,y_test))
print(recall_score(y_pred,y_test))
print(f1_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.85
0.6382978723404256
0.967741935483871
0.7692307692307693
[[72 17]
 [ 1 30]]


# Hyper Parameter tuning


## 1. Randomized CV

In [14]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV 
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf')
params = [{'C':[1,10,100,1000],'kernel':['rbf','linear']},
          {'C':[1,10,100,1000],'kernel':['rbf','linear'], 'gamma': [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
RandomizedCV = RandomizedSearchCV(estimator = classifier, 
                                            cv=10, 
                                            n_jobs=-1, 
                                            scoring='accuracy',
                                            param_distributions=params)

RandomizedCV.fit(x_scaled_data, y_train)

RandomizedSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
                   param_distributions=[{'C': [1, 10, 100, 1000],
                                         'kernel': ['rbf', 'linear']},
                                        {'C': [1, 10, 100, 1000],
                                         'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6,
                                                   0.7, 0.8, 0.9],
                                         'kernel': ['rbf', 'linear']}],
                   scoring='accuracy')

In [15]:
accuracy = RandomizedCV.best_score_
accuracy

0.9

In [16]:
RandomizedCV.best_params_

{'kernel': 'rbf', 'gamma': 0.3, 'C': 10}

In [17]:
classifier = SVC(kernel='rbf',gamma=0.2,C=100)
classifier.fit(x_scaled_data, y_train)
y_pred = classifier.predict(x_test_scaled_data)

In [18]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(precision_score(y_pred,y_test))
print(recall_score(y_pred,y_test))
print(f1_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.9166666666666666
0.9148936170212766
0.8775510204081632
0.8958333333333334
[[67  4]
 [ 6 43]]


## 2. Grid Search CV

In [19]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion='entropy')
DT.fit(x_scaled_data, y_train)
y_pred = DT.predict(x_test_scaled_data)

In [20]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(precision_score(y_pred,y_test))
print(recall_score(y_pred,y_test))
print(f1_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.8583333333333333
0.8085106382978723
0.8260869565217391
0.8172043010752689
[[65  9]
 [ 8 38]]


In [36]:
# max_leaf_nodes = 2^p (p=> no of predictors)
params = [{'criterion': ['entropy','gini','log_loss'],
           'max_depth':[1,3,5,10],
           'max_leaf_nodes':[2,4,8],
           'max_features':[1,2,3],
           'min_samples_leaf':[1,3,5],
           'min_samples_split':[2,3,5],
           #'ccp_alpha':[0.5,0.75,1],
           }]
DT = DecisionTreeClassifier()
GridCV = GridSearchCV(estimator=DT,
                      scoring='accuracy',
                      param_grid=params,
                      cv=10,
                      n_jobs=-1)

In [37]:
grid = GridCV.fit(x_scaled_data, y_train)

In [38]:
accuracy = grid.best_score_
accuracy

0.9

In [39]:
grid.best_params_

{'criterion': 'log_loss',
 'max_depth': 10,
 'max_features': 2,
 'max_leaf_nodes': 8,
 'min_samples_leaf': 3,
 'min_samples_split': 2}

In [40]:
classifier = DecisionTreeClassifier(criterion="log_loss",
                                    max_depth=10,
                                    max_features=2,
                                    max_leaf_nodes=8,
                                    min_samples_leaf=3,
                                    min_samples_split=2)
classifier.fit(x_scaled_data,y_train)
y_pred = classifier.predict(x_test_scaled_data)


In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(precision_score(y_pred,y_test))
print(recall_score(y_pred,y_test))
print(f1_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.925
0.9148936170212766
0.8958333333333334
0.9052631578947369
[[68  4]
 [ 5 43]]
